// src/vue/components/Stopwatch.vue
<template>
  <div>
    <h2>{{ time | toNumber }}</h2>

    <button v-on:click="start"
            v-bind:disabled="active">
      Start
    </button>
    <button v-on:click="stop"
            v-bind:disabled="!active">
      Stop
    </button>
    <button v-on:click="reset">
      Reset
    </button>


    <p v-if="previousTime + time > 0">
      Total elapsed time: {{ previousTime + time | toNumber }}
    </p>

    <ol>

      <li v-for="(time, index) in previousTimes"
          :key="index">
        {{ time | toNumber }}
      </li>
    </ol>
  </div>
</template>

<script>
export default {
  created() {
      this.subscription = null;
  },
  data() {
    return {
      time: 0.0,
      previousTimes: [],
      active: false
    };
  },
  computed: {
    previousTime () {
      return this.previousTimes.reduce((prev, cur) => prev + cur, 0);
    }
  },
  filters: {
    toNumber(value) {
      return value.toFixed(2);
    }
  },
  methods: {
    start() {
      if (this.active) return;

      this.active = true;
      this.subscription = setInterval(() =>
        this.time += 0.01, 10);
    },
    stop() {
      if (!this.active) return;

      this.active = false;
      clearInterval(this.subscription);
      this.subscription = null;
    },
    reset() {
      this.stop();
      this.previousTimes.push(this.time);
      this.time = 0.0;
    }
  }
}
</script>

// src/react/components/Stopwatch.jsx
import React from 'react';

export class Stopwatch extends React.Component {

  subscription = null;

  constructor() {
    super();

    this.state = {
      time: 0.0,
      previousTimes: [],
      active: false
    };

    this.previousTime = this.previousTime.bind(this);
    this.start = this.start.bind(this);
    this.stop = this.stop.bind(this);
    this.reset = this.reset.bind(this);
  }

  render() {
    return (
      <div>
        <h2>{ this.toNumber(this.state.time) }</h2>

        <button onClick={this.start}
                disabled={this.state.active}>
          Start
        </button>
        <button onClick={this.stop}
                disabled={!this.state.active}>
          Stop
        </button>
        <button onClick={this.reset}>
          Reset
        </button>

        { this.previousTime() + this.state.time > 0 && (
          <p>
            Total elapsed time: { this.toNumber(this.previousTime() + this.state.time) }
          </p> )}

        <ol>
          { this.state.previousTimes.map((time, index) =>
            <li key={index}>
              { this.toNumber(time) }
            </li>) }
        </ol>
      </div>
    );
  }

  previousTime() {
    return this.state.previousTimes.reduce((prev, cur) => prev + cur, 0);
  }

  toNumber(value) {
    return value.toFixed(2);
  }

  start() {
    if (this.state.active) return;

    this.setState({ active: true })
    this.subscription = setInterval(() =>
      this.setState({ time: this.state.time + 0.01 }), 10);
  }

  stop() {
    if (!this.state.active) return;

    this.setState({ active: false })
    clearInterval(this.subscription);
    this.subscription = null;
  }

  reset() {
    this.stop();
    this.setState({
      previousTimes: [ ...this.state.previousTimes, this.state.time ]
    });
    this.setState({
      time: 0.0
    });
  }
}
